<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>i</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>PowerISA-Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^
]*
</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|[ 	])\*(?![+-])[^
]*
</string>
			<key>name</key>
			<string>comment.line.asterisk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(\s*[a-zA-Z][a-zA-Z0-9_]*:)</string>
			<key>name</key>
			<string>meta.label.global.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((?i)([rv][0-9]|[rv][1-2][0-9]|[rv]3[0-1]|vs[0-9]|vs[1-5][0-9]|vs6[0-3]))?\b</string>
			<key>name</key>
			<string>storage.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(vadduhm|vadduhs|vmladduhm|vmrghb|vmrglb|vmuleub|vmuloub|vperm|vpkuhus|vspltish|vsrh)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.vmx.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(xxlnand|xxlnor|xxlxor|xxswapd)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.vsx.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(lwa|lxvd2x|lxvw4x|stxvd2x)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.memory.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addi|addis|li|lis)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.arithmetic.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(blr)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.control.PowerISA</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\billegal\b</string>
			<key>name</key>
			<string>invalid.illegal.opcode.PowerISA</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.PowerISA</string>
	<key>uuid</key>
	<string>375edd7a-cfa4-47d5-b8de-46e63a477897</string>
</dict>
</plist>
